[package]
name = "rarchive"
version = "0.1.0"
authors = ["Justus K <justus.k@protonmail.com>"]
edition = "2018"
license = "Zlib"

[workspace]
members = ["rarchive-sys"]

[dependencies]
rarchive-sys = { path = "./rarchive-sys" }
